apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmt-consulta-de-pessoas
  labels:
    app: bmt-consulta-de-pessoas
spec:
  replicas: 1  # Número de réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: bmt-consulta-de-pessoas
  template:
    metadata:
      labels:
        app: bmt-consulta-de-pessoas
    spec:
      containers:
        - name: bmt-consulta-de-pessoas
          image: bmt-consulta-de-pessoas:0.0.3-SNAPSHOT  # Imagem conforme o Docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # Porta do container, ajustada para 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bmt-consulta-de-pessoas-service
spec:
  selector:
    app: bmt-consulta-de-pessoas
  ports:
    - protocol: TCP
      port: 8080           # Porta exposta no Kubernetes (pode ser acessada por outros pods ou serviços)
      targetPort: 8080     # Porta interna do container
      nodePort: 30080      # Defina um número de porta exclusivo (garanta que não esteja em conflito)
  type: NodePort  # Tipo de serviço para comunicação externa
  # Caso precise expor o serviço para um IP específico, descomente a linha abaixo:
  # externalIPs:
  #   - 192.168.15.3  # IP externo que você deseja associar ao serviço
