apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmt-consulta-de-pessoas
  labels:
    app: bmt-consulta-de-pessoas
spec:
  replicas: 3  # Número de réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: bmt-consulta-de-pessoas
  template:
    metadata:
      labels:
        app: bmt-consulta-de-pessoas
    spec:
      containers:
        - name: bmt-consulta-de-pessoas
          image: bmt-consulta-de-pessoas:latest   # Imagem conforme o Docker
          ports:
            - containerPort: 8080  # Porta do container, ajustada para 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bmt-consulta-de-pessoas-service
spec:
  selector:
    app: bmt-consulta-de-pessoas
  ports:
    - protocol: TCP
      port: 80           # Porta exposta no Kubernetes (pode ser acessada por outros pods ou serviços)
      targetPort: 8080    # Porta interna do container
  type: ClusterIP  # Tipo de serviço para comunicação interna
